version: '3.7'

services:
   #banco de dados do postgres
  postgres-database: 
    container_name: postgres-database
    image: postgres:12.3
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data" 
    #Enviroment variable for DB name, user and password 
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
      POSTGRES_DB: transacoes
    ports:
      - 5432:5432

  #configuracao do jaeger para trace de log
  jaeger-service: 
    container_name: jaeger_service
    image: jaegertracing/all-in-one:1.17
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

 #configuracao do prometheus
  prometheus-service: 
    container_name: prometheus_service
    restart: always
    image: prom/prometheus:v2.17.2
    ports:
     - 9090:9090
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    
