version: "3.7"

services:
  #microservico de transacao
  transacao-jvm: 
    image: quarkus/transacoes-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL:  jdbc:postgres-database://localhost:5432/postgres
    networks:
      - pg-db    
    ports:
      - 8080:8080
    depends_on:
      - postgres-database

  #banco de dados do postgres
  postgres-database: 
    image: postgres:12.2
    environment:
      - POSTGRES_USER:=admin
      - POSTGRES_PASSWORD=admin
    ports:
       - "5432:5432"
    networks:
      - pg-db

networks:
 pg-db:
  driver: bridge
