version: '3.7'

services:

   #banco de dados do postgres
  postgres-database: 
    container_name: postgres-database
    image: postgres:12.3
    #network_mode: "bridge"
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data" 
    #Enviroment variable for DB name, user and password 
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
      POSTGRES_DB: transacoes
    ports:
      - 5432:5432
    networks:
      - minha-rede

  #microservico de transacao
  transacao-jvm: 
    container_name: ms_transacao
    image: quarkus/transacoes12-jvm:latest
    #network_mode: "bridge"
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      - DB_SERVER=postgres-database
      - POSTGRES_DB=transacoes
      - POSTGRES_USER=register
      - POSTGRES_PASSWORD=register
    ports:
      - 8080:8080
    depends_on:
      - postgres-database
    networks:
      - minha-rede

networks: 
  minha-rede:
    driver: bridge
