-- public.transacao definition

-- Drop table

-- DROP TABLE public.transacao;

CREATE TABLE public.transacao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bandeira varchar(255) NULL,
	localidade varchar(255) NULL,
	valor numeric(19,2) NULL,
	CONSTRAINT transacao_pkey PRIMARY KEY (id)
);

-- public.usuario definition

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cpf varchar(255) NULL,
	nome varchar(255) NULL,
	"password" varchar(255) NULL,
	"role" varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

-- public.ordem definition

-- Drop table

-- DROP TABLE public.ordem;

CREATE TABLE public.ordem (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"data" date NULL,
	preco float8 NULL,
	status varchar(255) NULL,
	tipo varchar(255) NULL,
	user_id int8 NULL,
	CONSTRAINT ordem_pkey PRIMARY KEY (id)
);