-- public.transacao definition

-- Drop table

-- DROP TABLE public.transacao;

CREATE TABLE public.transacao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bandeira varchar(255) NULL,
	localidade varchar(255) NULL,
	valor numeric(19,2) NULL,
	CONSTRAINT transacao_pkey PRIMARY KEY (id)
);

